[package]
name = "c3s"
version = "0.1.0"
authors = ["Pedro Dias <pdcmpa@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.5"
postgres = "0.17"
postgres-types = { version = "0.1", features = ["derive"]}
failure = { version = "0.1", features = ["derive"] }
